CREATE DATABASE IF NOT EXISTS appm DEFAULT CHARSET utf8 ;

CREATE TABLE IF NOT EXISTS `tb_appfile` (
  `id` bigint(20) NOT NULL DEFAULT '0',
  `UPLOADNAME` varchar(300) DEFAULT NULL,
  `APPPATH` varchar(60) DEFAULT NULL,
  `APPSAVENAME` varchar(300) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;





CREATE TABLE IF NOT EXISTS `tb_apptype` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `INTRO` varchar(100) DEFAULT NULL,
  `CREATEDATE` datetime DEFAULT NULL,
  `UPDATEDATE` datetime DEFAULT NULL,
  `ICON` varchar(100) DEFAULT NULL,
  `BACKGROUND` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=3 ;



INSERT INTO `tb_apptype` ( `INTRO`, `CREATEDATE`, `UPDATEDATE`, `ICON`, `BACKGROUND`) VALUES
( 'ios', NULL, NULL, 'icon-apple', 'bg-cyan'),
( 'android', NULL, NULL, 'icon-android', 'bg-green');


CREATE TABLE IF NOT EXISTS `tb_project` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `PROJECTNAME` varchar(60) DEFAULT NULL,
  `INTRO` varchar(300) DEFAULT NULL,
  `ICON` varchar(100) DEFAULT NULL,
  `CREATEDATE` datetime DEFAULT NULL,
  `UPDATEDATE` datetime DEFAULT NULL,
  `APPCODE` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=5 ;


INSERT INTO `tb_project` ( `PROJECTNAME`, `INTRO`, `ICON`, `CREATEDATE`, `UPDATEDATE`, `APPCODE`) VALUES
('test', '..."fdfdf', NULL, '2014-12-02 16:57:49', '2014-12-02 16:57:54', NULL),
('YaHooFrame', '...', NULL, '2015-01-14 11:41:34', '2015-01-14 11:41:34', NULL);



CREATE TABLE IF NOT EXISTS `tb_userrole` (
  `ID` decimal(10,0) DEFAULT NULL,
  `ROLENAME` varchar(30) DEFAULT NULL,
  `ROLEDESC` varchar(150) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `tb_users` (
  `ID` decimal(10,0) NOT NULL,
  `ROLEID` decimal(10,0) DEFAULT NULL,
  `USERNAME` varchar(30) DEFAULT NULL,
  `PWD` varchar(60) DEFAULT NULL,
  `CREATEDATE` datetime DEFAULT NULL,
  `REALNAME` varchar(30) DEFAULT NULL,
  `STATE` tinyint(4) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



INSERT INTO `tb_users` (`ID`, `ROLEID`, `USERNAME`, `PWD`, `CREATEDATE`, `REALNAME`, `STATE`) VALUES
('1', '1', 'admin', '57bf539359c8b184d10aa14dd009ccc8', NULL, NULL, NULL);



CREATE TABLE IF NOT EXISTS `tb_versions` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `APPTYPE` int(11) DEFAULT NULL,
  `VERSION` varchar(4000) DEFAULT NULL,
  `PROJECTNAME` varchar(4000) DEFAULT NULL,
  `CREATEDATE` datetime DEFAULT NULL,
  `UPDATEDATE` datetime DEFAULT NULL,
  `PROJECTID` decimal(10,0) DEFAULT NULL,
  `CONTENT` longtext,
  `IOSAPPEND` varchar(300) DEFAULT NULL,
  `APPFILE` bigint(20) DEFAULT NULL,
  `APPID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=8 ;


